"""empty message

Revision ID: 24bbfc43d562
Revises: 6e6b050429cb
Create Date: 2018-03-08 14:14:46.307037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bbfc43d562'
down_revision = '6e6b050429cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
